### ISSUE TITLE
Update for Atramhasis 2.0.0

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis_demo_cookiecutter#19]
The current version was written for 1.3.x. Some updates for 2.0.0 are needed, especially in configuring the database. The demo providers should be in the database.

**Comment by Wim-De-Clercq** [comment]
Correct. I have the feeling I want to partially fix this in Atramhasis. Currently the `initializedb` / `initialize_atramhasis_db` script fills the database with concepts and conceptschemes, but does not create the providers.

There is of course the migration script which would do that for you. That is nice for pre-existing instances which need to migrate and I could of course simply document in the readme to first run initialize DB and then run migration. 
But I feel that a new run of the initialize DB script should automatically do the providers as well, I find it a bit ugly to immediately require a migration on a new setup. I'll make an issue at atramhasis for this. (https://github.com/OnroerendErfgoed/atramhasis/issues/848)


There is still a fix needed in this project to read the providers from the DB during the startup in the `skos/__init__.py` file.
