### ISSUE TITLE
The demo site does not have demo data when run

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis_demo_cookiecutter#2]
The file https://github.com/OnroerendErfgoed/atramhasis_demo_cookiecutter/blob/main/%7B%7Bcookiecutter.repo%7D%7D/%7B%7Bcookiecutter.package%7D%7D/skos/__init__.py should probably be identical (or very similar) to https://github.com/OnroerendErfgoed/atramhasis/blob/0.7.0/atramhasis/scaffolds/atramhasis_demo/%2Bpackage%2B/skos/__init__.py_tmpl

**Comment by goessebr** [comment]
This was probably an issue with the documention and is fixed via https://github.com/OnroerendErfgoed/atramhasis_demo_cookiecutter/commit/d9356c41b2fb066eb0e4f40f4538fd0ad91b1352.

I still have some difficulties with the demo data from external sources though: #10
